export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_PENDING = "REGISTER_USER_PENDING";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";


export const SET_USER_AUTHORIZED = "SET_USER_AUTHORIZED";

export const GET_REGENT_CHARTS = "GET_REGENT_CHARTS";
export const GET_REGENT_CHARTS_PENDING = "GET_REGENT_CHARTS_PENDING";
export const GET_REGENT_CHARTS_SUCCESS = "GET_REGENT_CHARTS_SUCCESS";
export const GET_REGENT_CHARTS_FAILED = "GET_REGENT_CHARTS_FAILED";

export const UPDATE_REGENT_CHARTS = "UPDATE_REGENT_CHARTS";
export const UPDATE_REGENT_CHARTS_PENDING = "UPDATE_REGENT_CHARTS_PENDING";
export const UPDATE_REGENT_CHARTS_SUCCESS = "UPDATE_REGENT_CHARTS_SUCCESS";
export const UPDATE_REGENT_CHARTS_FAILED = "UPDATE_REGENT_CHARTS_FAILED";